### ISSUE TITLE
On Dyalog 19.0 the function NuGet.Using does not accept a serialized namespace with curly braces as left parameter anymore

### ISSUE THREAD

**Issue by Alexander-Block** [Dyalog/nuget#14]
The function `NuGet.Using` is meant to accept a JSON5 string as left option argument which is internally converted to a Dyalog APL namespace. This conversion uses a call to `⎕SE.Dyalog.Array.Deserialise` without left parameter. The semantics of `⎕SE.Dyalog.Array.Deserialise` seems to have changed with the release of Dyalog APL 19.0, which leads to this conversion not working as expected anymore:
```APL
      ⎕SE.Dyalog.Array.Deserialise '{includePrimary : 0}'
     ∇{includePrimary:0}
     ∇
```
This in turn leads to a call to `NuGet.Using` with a JSON5 string left argument failing with a DOMAIN ERROR. I have described an example of this error in [this Cider issue](https://github.com/aplteam/Cider/issues/62).

**Comment by Alexander-Block** [comment]
I have filed a corresponding issue for the NuGet api [here](https://github.com/Dyalog/nuget/issues/14).

**Comment by mkromberg** [comment]
I think the old version of Deserialise accepted the incorrect use of curly braces to denote a namespace. The correct notation is to use parentheses:

      NuGet.Using project_dir
 ,/tmp/nuget-test/published/Clock.dll  ,/tmp/nuget-test/published/nuget-test.dll 
      '(includePrimary:0)' NuGet.Using project_dir
 ,/tmp/nuget-test/published/Clock.dll

**Comment by Alexander-Block** [comment]
Thank you for the very fast response, @mkromberg! That makes a lot of sense considering that JSON5 notation can clash with defn notation. 

Unfortunately it was not only my impression that curly braces are okay in this context, but it is currently part of the documentation [here](https://github.com/Dyalog/nuget/blob/7f89e360d06e19a7fa986516454fbbcc2c24ba31/README.md?plain=1#L52).

I think that the documentation should be changed accordingly and this API change may break the setup of projects that used NuGet under Dyalog APL 18.2 before (which admittedly may only be Cider whose problem should be solved with this [PR](https://github.com/aplteam/Cider/pull/63)). The other option would be to change from a use of `⎕SE.Dyalog.Array.Deserialise` to `⎕JSON` with fitting option parameters, but if I understand you correctly that may clash with the general API template you envsion for passing options to APL functions.

**Comment by mkromberg** [comment]
Yes, so it is I who has led you astray, I will correct the documentation today. I suspect your PR is all that is required at this point. Apologies and thanks for catching this and reporting it!

**Comment by mkromberg** [comment]
I did not read your report carefully enough: To be precise, the left argument is not JSON5, it is APL Array Notation. A bug in the old implementation allowed curly braces.

**Comment by Alexander-Block** [comment]
Thank you for the explanation. That clears up my main misunderstanding. I hadn't worked with APL array notation for namespaces before and - based on the example in the README - thought that JSON5 was _the_ way to serialize namespaces in Dyalog APL. It is good to know that this is not the case.
