### ISSUE TITLE
Investigate removing ⎕IO.apla and ⎕ML.apla as they cause problems with packaging on various platforms - and cider.config sets them

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/nuget#16]
`⎕IO.apla` and `⎕ML.apla` cause problems with packaging.  Create a zip file with them on Windows and unzip elsewhere, and the `⎕` has been transformed into something else.  Similarly if you zip up on non-Windows and unzip on Windows.

Additionally, are the files needed anyway as cider.config contains
```
SYSVARS: {
    io: 1,
    ml: 1,
}
```

NuGet at [30d95d1](https://github.com/Dyalog/nuget/commit/30d95d17deac0f1c7d88d1a54bfb70bc293d9e8a)

**Comment by aplteam** [comment]
With the next version of Tatin, the newly introduced' exclude' keyword will allow you to prevent particular files and folders from becoming members of the Tatin package.

The files are useful in case `nuget` is consumed not as a package but downloaded from GitHub.

**Comment by xpqz** [comment]
Closing after discussion with @mkromberg
