### ISSUE TITLE
Missing ⊃ at Setup[4]

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/nuget#2]
While discussing an error related to .NET and mac, @dyaandys remarked this

> As a matter of interest, how can 4↑(TFM RID) return a simple 4 element vector – clearly my APL is even less competent than I thought it was ☹.

concerning the statement 
`Setup[4] :If 'net4'≡4↑(TFM RID)←GetDotNetIDS ⍬
 `

**Comment by mkromberg** [comment]
There is fairly obviously a ⊃ missing, we are trying to compare the TFM (Target Framework Moniker). I will deal with this and tidy up a few other things before the Beta of v19.0+ goes out.

**Comment by aplteam** [comment]
> There is fairly obviously a `⊃` missing,...

And the `4↑` is superfluous:

` :If 'net4'≡⊃(TFM RID)←GetDotNetIDS ⍬`

is sufficient. However, it is also  a good demonstration of why this should go onto two different lines:

```
(TFM RID)←GetDotNetIDS ⍬ 
:If 'net4'≡TFM
```

But that does not answer  @dyaandys question:

> As a matter of interest, how can 4↑(TFM RID) return a simple 4 element vector – clearly my APL is even less competent than I thought it was ☹.

The result will only be simple if both `TFM` and `RID` are scalars, for example:

```
      ≡4↑' ' 0
1
```

**Comment by mkromberg** [comment]
I did not answer Andy's question because I believe it to be rhetorical :).

What actually went wrong here is a an attempt to do a "minimal refactoring" after a function which only returned an approximation of the TFM was replaced by one that returned both TFM and RID.

The 4↑ is *NOT* superfluous, as the TFM is likely to be something like "net48" in the case of the .NET framework.

**Comment by aplteam** [comment]
Ah, one of those nasty cases when the APL can only be fully appreciated if one happens to have sufficient knowledge of the data involved...

**Comment by mkromberg** [comment]
I think you will find that this applies to almost all programming :)
